### ISSUE TITLE
Page 8 (Tools): Introduction is missing 

### ISSUE THREAD

**Issue by rcschrg** [NFDI4Energy/EFZN_rdm#14]
The tools page is suddenly appearing without any real introduction. At least a transition would be generally nice.

**Comment by thomaswolgast** [comment]
I agree. And some examples for every entry would be helpful as well. In the best case, the user can immediately identify some relevant tools for himself/herself.

**Comment by JuliaHeiken** [comment]
@thomaswolgast could you please come up with an introduction as well?

**Comment by sferenz** [comment]
I think this can be improved by #74
