### ISSUE TITLE
Page 14 1/4: Low quality image

### ISSUE THREAD

**Issue by rcschrg** [NFDI4Energy/EFZN_rdm#18]
Replace with vector graphic

**Comment by JuliaHeiken** [comment]
Please do so :) you can find the images in the cloud.

**Comment by rcschrg** [comment]
The picture is from this article: https://www.frontiersin.org/articles/10.3389/fclim.2021.763420/full . As discussed, look up a better image for the section. Thank you!

**Comment by sferenz** [comment]
I created an improved version of the image - will be added later
