### ISSUE TITLE
Make definition of RDM clear with example

### ISSUE THREAD

**Issue by emiliefro** [NFDI4Energy/EFZN_rdm#20]
Explain definition of RDM with an example (maybe the one given in the introduction)? This way, principle does not really become clear. How could it have worked better in the given example?
Its on page 2

**Comment by sferenz** [comment]
@emiliefro Can you please check out the new examples in the branch? Do you think, they work better?

**Comment by emiliefro** [comment]
@sferenz I did, i like the new examples :-)
