### ISSUE TITLE
page 8 (1/3): Confusing structure

### ISSUE THREAD

**Issue by thomaswolgast** [NFDI4Energy/EFZN_rdm#33]
I have multiple problems here. 
1. The first step of choosing a suitable tool is choosing the tool?! On what basis do you make the decision?
2. Here we have multiple exemplary tools. However, there is no connection to the previous page (0/3). Can all these tools provide all the features mentioned there?
3. ~~Some Tools have names, some have URLs. This should be consistent.~~ I fixed this in my branch already
4. Maybe a short introduction to the three categories would be helpful. What are the differences? When to use which category?

**Comment by JuliaHeiken** [comment]
@thomaswolgast in our opinion, the steps can be replaced by a text that explains the following categories (table) and include aspects to consider when choosing a tool.

**Comment by thomaswolgast** [comment]
I added a description of the three categories (in my understanding). However, I don't really have the expertise to write a guide on which tool to use in which situation.
