### ISSUE TITLE
page 8 (2/3): Task too difficult

### ISSUE THREAD

**Issue by thomaswolgast** [NFDI4Energy/EFZN_rdm#34]
Maybe I'm too stupid but this is far too difficult IMO. I started with [RDMO](https://rdmorganiser.github.io/en/). There, the installation seems to be quite cumbersome. Therefore, I switched to the online tool [DMPOnline](https://dmponline.dcc.ac.uk/). There, I created an account but still can't log in. Here, I gave up... 

At least suggest an easy-to-use tool here. In case of DMPOnline, maybe even provide login data. In the current state, no one will actually do this task. And then it can be removed.

**Comment by JuliaHeiken** [comment]
I could create an account at DMPOnline. The use of DMPOnline is pretty straight-forward in my opinion..

**Comment by thomaswolgast** [comment]
Now the login for DMPOnline worked and I agree that it is pretty straightforward to use. I would add a recommendation for DMPOnline to page 8 (2/3) to reduce the barrier for users to actually test such a tool. I still think, users would not do such a task if it requires the installation of a tool beforehand.
