### ISSUE TITLE
Page 8 (3/3): Quiz 4/7 impossible to solve

### ISSUE THREAD

**Issue by thomaswolgast** [NFDI4Energy/EFZN_rdm#35]
See figure below. It is impossible to know which word should come before and after the "or". This is just frustrating for the user. 

![grafik](https://github.com/NFDI4Energy/EFZN_rdm/assets/41008623/8ad64ced-e6c1-4fb1-b617-3299c3af1291)

**Comment by JuliaHeiken** [comment]
change quiz, less blanks
