### ISSUE TITLE
Page 12 : Only NFDI

### ISSUE THREAD

**Issue by thomaswolgast** [NFDI4Energy/EFZN_rdm#37]
Here, the user expects some information about infrastructure. However, the only thing he/she gets is information about NFDI, which is still in the beginning. For the normal user, this is not helpful at all because no actual solutions are presented.

**Comment by JuliaHeiken** [comment]
Add additional text above the video, discuss with Thomas.

**Comment by sferenz** [comment]
@thomaswolgast I removed the video and changed the text. Also, I improved the tools chapter into this one, because I think it fits well here. What do you think?

**Comment by thomaswolgast** [comment]
I think it's improved this way. I also added a minor language fix. 

However, I don't really see any meaningful diff of the tools section, because everything is marked as "changed"
