### ISSUE TITLE
Page 10: Contradiction between course content and quiz

### ISSUE THREAD

**Issue by pht-uol** [NFDI4Energy/EFZN_rdm#42]
In front at (1/3) it says: NoDerivatives (ND): This license allows reusers to copy and distribute the material in unadapted form only. But in the sixth quiz it says that others may only use the work unchanged. This is imho a stronger restriction than the one in front (but this agrees with Wikipedia).

**Comment by JuliaHeiken** [comment]
We should make the wording clear according to https://creativecommons.org/licenses/by-nd/4.0/ in both the text and the quiz.
