### ISSUE TITLE
Page 2: Description of critical systems looses reader

### ISSUE THREAD

**Issue by pht-uol** [NFDI4Energy/EFZN_rdm#45]
In the second paragraph, some kind of critical systems fail due to "overload of critical systems". However, the text does not lead the reader and she remains unknown of what kind of systems she should have in mind. This costs important attention so early in the course.

**Comment by JuliaHeiken** [comment]
The issue is also addressed in https://github.com/NFDI4Energy/EFZN_rdm/issues/11.
