### ISSUE TITLE
Page 8: Introduction to scope of the tools confusing

### ISSUE THREAD

**Issue by pht-uol** [NFDI4Energy/EFZN_rdm#47]
What exactly should this section be about and especially for which part of RDM are the tools intended? Till here, the course mentioned RDM incl. meta data, the actual research data and the data management plan. For all of them, I can imagine that there is help through tools. But especially at the beginning of this section I don't feel picked up, because questions arise in my head which are not answered by the text nor the voice.

**Comment by JuliaHeiken** [comment]
@thomaswolgast please keep this in mind when improving the "Tools" section.

**Comment by JuliaHeiken** [comment]
Will be done by #74
