### ISSUE TITLE
Page 8 (3/3): Crazy error message and pop-up window

### ISSUE THREAD

**Issue by pht-uol** [NFDI4Energy/EFZN_rdm#49]
Sometimes while positioning word in the text of quiz "Which factor should you consider...?" an error message shows up "Reset drop
Are you sure you want to reset this drop zone?". First, it happened when I tried to insert "expertise" without having filled some of the previous fields. Later it happened again in different situations and other quizzes.

**Comment by JuliaHeiken** [comment]
Could you please add more information like a step-by-step instruction for reproducing this bug or a screen recording and which browser you use etc?

**Comment by pht-uol** [comment]
It was Firefox 101.0.1 (64-Bit)

**Comment by JuliaHeiken** [comment]
I will close this then.
