### ISSUE TITLE
Page 8 (3/3): Quiz is irritating

### ISSUE THREAD

**Issue by pht-uol** [NFDI4Energy/EFZN_rdm#50]
During solving the puzzle, different factor lead to distraction causing frustration:
- The boxes have quite uneven sizes.
- The sizes of the boxes to not fit to the cards that belong there.
- When placing cards in the boxes, they jump into the top left corner of the box.
- In the background pic, the staircase goes from bottom to top and not from top to bottom as the cards have to be ordered

Suggestion: order sequences from top to bottom and not vice versa (probably choose another photo).

**Comment by JuliaHeiken** [comment]
quiz will be deleted/changed
