### ISSUE TITLE
Downloadable example data management plan partly in German

### ISSUE THREAD

**Issue by JuliaHeiken** [NFDI4Energy/EFZN_rdm#7]
The questions in the example data management plan (https://raw.githubusercontent.com/NFDI4Energy/EFZN_rdm/Julia_%C3%9Cberarbeitung/img/DMP_GridCapacity.pdf) are in German. For consistency, they should be in English.

**Comment by JuliaHeiken** [comment]
@emiliefro could you provide your DMP when you finished your first one for NFDI?

**Comment by emiliefro** [comment]
> @emiliefro Is it possible to provide an English example until the Conference (20.02.)?

Yes!
