### ISSUE TITLE
Move tools to infrastructure

### ISSUE THREAD

**Issue by sferenz** [NFDI4Energy/EFZN_rdm#74]
From my perspective tools are part of the relevant infrastructure for RDM. Therefore, I think the chapter about tools should be moved there. What do you think?

**Comment by JuliaHeiken** [comment]
We could do that, but I would like to keep the Tools section right after the Data Management Plan section, because they are related by the DMP task. So, either "DMP" - "Infrastructure" - "Legal Aspects" or "Legal Aspects" - "DMP" - "Infrastructure". Do you agree?

**Comment by sferenz** [comment]
Yes, then I would prefer to move the Legal Aspects to the end. Do you agree with that?

**Comment by JuliaHeiken** [comment]
Fine with me.
